name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: print 
        run: echo "hello I was here "
        
      - name: Install p2o
        run: npm install -g p2o
        
      - name: Run p2o command
        run: p2o ./api.json -f ./result.yml

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update result.yml"
          git push
