name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Debug File Permissions
        run: |
          ls -l .github/runP2O.js 
          ls -l .github/result.yml
          
      - name: Modify File Permissions
        run: chmod 666 .github/result.yml 
        
      - name: Modify File Permissions
        run: chmod 666 .github/runP2O.js 
        
      - name: Debug File Permissions
        run: |
          ls -l .github/runP2O.js 
          ls -l .github/result.yml  
          
      - name: Install p2o
        run: npm i postman-to-openapi -g
  
      - name: Run p2o command using file
        run:  node .github/runP2O.js 

      - name: Display file contents
        run: |
          cat .github/result.yml
          
      - name: print secret
        run: echo ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Add changes
        run: git add .

      - name: Commit changes
        run: git commit -m "Auto-commit changes"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          github_token: ${{ secrets.PAT_TOKEN }}
