name: CI/CD Workflow

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  foo:
    runs-on: ubuntu-latest
    name: fooName
    steps:
    - name: label swapping
      uses: jinmayamashita/ready-for-review@1.0.0
      with:
        in-progress-label: 'my InProgress label'
        ready-for-review-label: 'my ReadyForReview label'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
            
          
     
